name: Pipeline CI - Qualidade e Automação

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  testes-api:
    name: 🟢 Testes de Back-end (Mocha)
    runs-on: ubuntu-latest
    # Diz ao GitHub para rodar todos os comandos deste Job dentro da pasta 'api'
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: 📥 Baixar o código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 📦 Instalar dependências da API
        run: npm ci --legacy-peer-deps

      - name: 🔍 Executar testes da API
        run: npm run test:api

  testes-web:
    name: 🔵 Testes de Front-end (Cypress)
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Baixar o código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 🚀 Iniciar API em Background
        working-directory: ./api
        run: |
          npm ci --legacy-peer-deps
          npm start &

      - name: 🌐 Executar Cypress E2E
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./web
          build: npm run build
          start: npm run preview
          # Aguarda a API (3000) e o Front-end de Produção (4173) estarem vivos
          wait-on: "http://localhost:3000, http://localhost:4173"
